version: '3'
services:

  bot:
    image: ghcr.io/bte-germany/eventbot:latest
    depends_on:
      - postgres
    ports:
      - "6969:6969"
    env_file:
    - .env
    environment:
      - DATABASE_URL=postgresql://prisma:prisma@postgres:5432/db
    links:
      - postgres
    restart: on-failure

  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      -  "6970:5432"
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_MULTIPLE_DATABASES=db
    volumes: 
      - event-bot-db:/var/lib/postgresql/data
      - ./PostgreSQL:/docker-entrypoint-initdb.d
    restart: on-failure


volumes:
  event-bot-db:
    driver: local
