version: '3'
services:

  bot:
    image: ghcr.io/bte-germany/eventbot:latest
    depends_on:
      - postgres
    ports:
      - "6969:6969"
    env_file:
    - .env
    environment:
      - DATABASE_URL=postgresql://prisma:prisma@postgres:5432/db
    links:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=db
    volumes: 
      - event-bot-db:/var/lib/postgresql/data
  
  NoCoDB:
    image: nocodb/nocodb:latest
    volumes: 
      - event-nocodb:/usr/app/data/
    ports:
      -  6970:8080
    environment:
      - NC_DB=postgresql://prisma:prisma@postgres:5432/db
      - NC_AUTH_JWT_SECRET=XkDXpPjr3scXVNRM4BhYfR8aTF6htLNcZD9NKJqWKvJrj27rgp8huinsxGezeWXsdHgwQ6Eydiuna9SzS5kAVcKA2xhuu4ndpKBFK7pGQQ3eT8WYbQifqteEUCqnze3M


volumes:
  event-bot-db:
    driver: local
  event-nocodb:
    driver: local